//
// Created by smart on 6/8/2016.
//

#ifndef LIGHTBOARD_CONFIG_H
#define LIGHTBOARD_CONFIG_H
#define NUM_LEDS 30
#define CHANNEL_BIT 8
#define COLOR_CHANNELS 3
#define DISTANCE_CALIBRATION 400
#define MAX_JUMP_HEIGHT 114
#define MIN_JUMP_HEIGHT 11
#define MAX_AMOUNT_OF_HIGHSCORE 10
#endif //LIGHTBOARD_CONFIG_H
