//
// Created by smart on 6/8/2016.
//

#ifndef LIGHTBOARD_CONFIG_H
#define LIGHTBOARD_CONFIG_H
#define NUM_LEDS 32
#define CHANNEL_BIT 8
#define COLOR_CHANNELS 3
#define DISTANCE_CALIBRATION 400
#endif //LIGHTBOARD_CONFIG_H
